# Generated by Django 4.2.2 on 2023-07-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='ac_status',
            field=models.CharField(choices=[('사고발생', '사고발생'), ('조치완료', '조치완료'), ('조치 중', '조치 중')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manage',
            name='position',
            field=models.CharField(choices=[('관리자', '관리자'), ('반장', '반장'), ('감독', '감독')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wearable',
            name='degree_safety',
            field=models.IntegerField(choices=[(1, '관심'), (2, '주의'), (4, '심각'), (3, '경계'), (0, '양호')], null=True),
        ),
        migrations.AlterField(
            model_name='wearable',
            name='hook',
            field=models.IntegerField(choices=[(0, '체결'), (2, '불량체결'), (1, '미체결')], null=True),
        ),
    ]
