# Generated by Django 4.2.2 on 2023-07-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_accident_ac_status_alter_manage_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='ac_status',
            field=models.CharField(choices=[('조치 중', '조치 중'), ('사고발생', '사고발생'), ('조치완료', '조치완료')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('감독', '감독'), ('반장', '반장'), ('관리자', '관리자')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manage',
            name='position',
            field=models.CharField(choices=[('감독', '감독'), ('반장', '반장'), ('관리자', '관리자')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='scl_status',
            field=models.CharField(choices=[('양호', '양호'), ('주의', '주의'), ('심각', '심각')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wearable',
            name='degree_safety',
            field=models.IntegerField(choices=[(2, '주의'), (0, '양호'), (4, '심각'), (1, '관심'), (3, '경계')], null=True),
        ),
        migrations.AlterField(
            model_name='wearable',
            name='hook',
            field=models.IntegerField(choices=[(1, '미체결'), (2, '불량체결'), (0, '체결')], null=True),
        ),
    ]
