# Generated by Django 4.2.5 on 2023-09-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_accident_ac_status_alter_employee_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='ac_status',
            field=models.CharField(choices=[('조치완료', '조치완료'), ('조치 중', '조치 중'), ('사고발생', '사고발생')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('관리자', '관리자'), ('반장', '반장'), ('감독', '감독')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manage',
            name='position',
            field=models.CharField(choices=[('관리자', '관리자'), ('반장', '반장'), ('감독', '감독')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='safety',
            name='scl_status',
            field=models.CharField(choices=[('주의', '주의'), ('양호', '양호'), ('심각', '심각')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wearable',
            name='hook',
            field=models.IntegerField(choices=[(2, '불량체결'), (0, '체결'), (1, '미체결')], null=True),
        ),
    ]
